kind: Service
apiVersion: v1
metadata:
  name: nginx-demo-service
  namespace: nginx-demo
spec:
  selector:
    app: nginx-demo
  type: LoadBalancer
  ports:
  - name:  app-port
    port:  80
    targetPort:  80